name: Flutter Build

on:
  workflow_dispatch:

env:
  MY_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Print Flutter version
        run: flutter --version

      - name: Create Flutter project
        run: |
          flutter create flutter_so
          cd flutter_so
          flutter pub get

      - name: Build apk for arm64 and armeabi-v7a
        run: |
          cd flutter_so
          flutter build apk --release --target-platform android-arm,android-arm64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.MY_TOKEN }}
        with:
          tag_name: flutter-v3.19.5
          release_name: Flutter Release v3.19.5
          draft: false
          prerelease: false

      - name: Upload libflutter.so for arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ env.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: flutter_so/build/app/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libflutter.so
          asset_name: libflutter_so_arm64.so
          asset_content_type: application/octet-stream

      - name: Upload libflutter.so for armeabi-v7a
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ env.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: flutter_so/build/app/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libflutter.so
          asset_name: libflutter_so_armeabi_v7a.so
          asset_content_type: application/octet-stream
