name: GitHub Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  cleanup:
    name: GitHub Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          repo: ${{ github.repository }}
          keep_latest: 0
